### ISSUE TITLE
Show installed versions of proton on install

### ISSUE THREAD

**Issue by rockerBOO** [auyer/Protonup-rs#32]
Love this application! One little thing I was looking for was after it installed to say which version it did install. It says it during the install process but after it would be nice to have it say which was installed.

```
$ protonup-rs
> ProtonUp Menu: Choose your action: Quick Update (detect apps and auto download)
Found the following apps: Steam "Native" , Lutris "Native"
```

Like this is the final frame and all the install process info isn't shown so not sure which was installed. 

I can try to get a PR together if desired. 

Thanks.

**Comment by auyer** [comment]
Hi! It sounds like a good improvement !
Since you offered to create a PR, feel free to do it, and to contact me if you need help.
