### ISSUE TITLE
Quick update (flatpak) downloads to wrong directory

### ISSUE THREAD

**Issue by evanc577** [auyer/Protonup-rs#4]
Using the quick update option with flatpak steam downloads the file to the normal steam directory not the flatpak directory.

I believe this line is the issue: https://github.com/auyer/Protonup-rs/blob/1e8c07e10121818efca3996e5785346942f473bd/protonup-rs/src/main.rs#L235

**Comment by auyer** [comment]
Thank you for pointing this out!
I just fixed it, and will make a new release on the next minutes.
